/**
 * Content pipeline (Phase 2 scaffold).
 *
 * Phase 1 ships a stub that generates an EMPTY registry so the app, build and
 * CI stay green. Phase 2 replaces the internals with:
 *   1. Discovery  — glob content dirs for tech.json and module lesson.mdx
 *   2. Validation — Zod schemas from types/content.ts
 *   3. Compilation— MDX bodies + esbuild-bundled validators
 *   4. Extraction — headings/text for navigation and search
 *   5. Emission   — lib/generated/content-registry.ts + search-index.json
 *
 * See docs/CONTENT_SCHEMA.md.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = path.join(ROOT, "lib", "generated");
const REGISTRY_PATH = path.join(OUT_DIR, "content-registry.ts");
const SEARCH_INDEX_PATH = path.join(OUT_DIR, "search-index.json");

const registryStub = `/* AUTO-GENERATED by scripts/build-content.ts — do not edit. */
import type { RegisteredLesson, RegisteredTechnology } from "@/types/content";

export const technologies: RegisteredTechnology[] = [];

export const lessons: RegisteredLesson[] = [];

export function getTechnology(slug: string): RegisteredTechnology | undefined {
  return technologies.find((t) => t.slug === slug);
}

export function getLessonsByTechnology(technologySlug: string): RegisteredLesson[] {
  return lessons.filter((l) => l.technologySlug === technologySlug);
}

export function getLessonBySlug(slug: string): RegisteredLesson | undefined {
  return lessons.find((l) => l.slug === slug);
}
`;

const searchIndexStub = {
  documents: [],
  generatedAt: new Date().toISOString(),
};

export function buildContent(): void {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(REGISTRY_PATH, registryStub, "utf8");
  writeFileSync(SEARCH_INDEX_PATH, JSON.stringify(searchIndexStub, null, 2), "utf8");
}

buildContent();

console.log("[content] stub registry written to lib/generated/ (full pipeline lands in Phase 2)");
