/**
 * Content pipeline.
 *
 * Discovers `content/`, validates it with Zod, compiles MDX to ESM, bundles
 * challenge validators with esbuild, extracts headings/text for navigation and
 * search, and emits the typed registry (`lib/generated/content-registry.ts`)
 * plus the search index (`lib/generated/search-index.json`).
 *
 * Adding a technology or lesson is purely additive — no app code changes.
 * See docs/CONTENT_SCHEMA.md and docs/ARCHITECTURE.md.
 */

import { build } from "esbuild";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { globSync } from "glob";
import matter from "gray-matter";

import { learningPaths } from "@/config/learning-paths";
import { compileMdx } from "@/lib/content/mdx";
import {
  challengeSchema,
  lessonFrontmatterSchema,
  moduleSchema,
  technologySchema,
} from "@/lib/content/schema";
import { iconMap } from "@/lib/icons";
import type { BundledValidator } from "@/validators/types";
import type {
  ChallengeMetadata,
  ModuleMeta,
  RegisteredLesson,
  RegisteredModule,
  RegisteredTechnology,
  TechnologyDocName,
} from "@/types/content";

/** Repository root; the launcher (`scripts/content-build.mjs`) sets CODIQ_ROOT. */
const ROOT = process.env.CODIQ_ROOT ?? process.cwd();
const OUT_DIR = path.join(ROOT, "lib", "generated");
const REGISTRY_PATH = path.join(OUT_DIR, "content-registry.ts");
const SEARCH_INDEX_PATH = path.join(OUT_DIR, "search-index.json");
const VALIDATOR_SOURCES_PATH = path.join(OUT_DIR, "validator-sources.ts");
const MDX_OUT_DIR = path.join(OUT_DIR, "mdx");
const VALIDATORS_OUT_DIR = path.join(OUT_DIR, "validators");

const TECH_DOC_NAMES: TechnologyDocName[] = [
  "intro",
  "installation",
  "structure",
  "best-practices",
  "summary",
];

/** Example file names tried for a lesson's runnable example. */
const EXAMPLE_FILENAMES = ["example.tsx", "example.jsx", "example.ts", "example.js"];

interface SearchDocument {
  id: string;
  type: "technology" | "module" | "lesson";
  title: string;
  description: string;
  slug: string;
  url: string;
  technologySlug?: string;
  moduleSlug?: string;
  tags: string[];
  content: string;
}

interface LessonEntry {
  lesson: RegisteredLesson;
  techOrder: number;
}

interface ModuleAgg {
  techSlug: string;
  moduleSlug: string;
  /** Metadata from `module.json`, or null until derived from the first lesson. */
  meta: ModuleMeta | null;
  lessons: RegisteredLesson[];
}

/** `${techSlug}/${moduleSlug}` → raw IIFE validator bundle source. */
const validatorSources = new Map<string, string>();

const errors: string[] = [];

function pushError(message: string): void {
  errors.push(message);
}

function formatError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

async function safeRun<T>(label: string, fn: () => Promise<T> | T): Promise<T | undefined> {
  try {
    return await fn();
  } catch (error) {
    pushError(`${label}: ${formatError(error)}`);
    return undefined;
  }
}

function readJson(filePath: string): unknown {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

/** glob returns native separators on Windows; normalize to POSIX for path.posix. */
function toPosix(relativePath: string): string {
  return relativePath.split(path.sep).join("/");
}

function contentGlob(pattern: string): string[] {
  return globSync(pattern, { cwd: ROOT }).map(toPosix).sort();
}

function writeCompiled(relPath: string, code: string): void {
  const abs = path.join(OUT_DIR, relPath);
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, `/* AUTO-GENERATED by scripts/build-content.ts — do not edit. */\n${code}`, "utf8");
}

async function bundleValidator(techSlug: string, moduleSlug: string): Promise<BundledValidator | undefined> {
  const entry = path.join(ROOT, "content", techSlug, "modules", moduleSlug, "validator.ts");
  const outRel = `validators/${techSlug}-${moduleSlug}.js`;
  try {
    const result = await build({
      entryPoints: [entry],
      bundle: true,
      write: false,
      format: "iife",
      platform: "browser",
      target: "es2020",
      // Expose the bundle's exports object as `window.__codiqValidator` so the
      // sandbox bootstrap can reach it when the bundle is inlined via srcdoc.
      globalName: "__codiqValidator",
      alias: { "@": ROOT },
      logLevel: "silent",
    });
    const output = result.outputFiles[0];
    if (!output) throw new Error("esbuild produced no output");
    const source = `/* AUTO-GENERATED validator bundle for ${techSlug}/${moduleSlug} — do not edit. */\n${output.text}`;
    writeFileSync(path.join(OUT_DIR, outRel), source, "utf8");
    return { path: outRel, source };
  } catch (error) {
    pushError(`validator ${techSlug}/${moduleSlug}: ${formatError(error)}`);
    return undefined;
  }
}

function findExamplePath(techSlug: string, moduleSlug: string): string | undefined {
  for (const fileName of EXAMPLE_FILENAMES) {
    const rel = path.join("content", techSlug, "modules", moduleSlug, fileName);
    if (existsSync(path.join(ROOT, rel))) return rel;
  }
  return undefined;
}

async function parseChallenge(techSlug: string, moduleSlug: string): Promise<ChallengeMetadata | undefined> {
  const rel = path.join("content", techSlug, "modules", moduleSlug, "challenge.json");
  if (!existsSync(path.join(ROOT, rel))) return undefined;

  const data = await safeRun(rel, () => readJson(path.join(ROOT, rel)));
  if (!data) return undefined;
  const parsed = await safeRun(`${rel} schema`, () => challengeSchema.parse(data));
  if (!parsed) return undefined;

  const challenge: ChallengeMetadata = {
    title: parsed.title,
    description: parsed.description,
    difficulty: parsed.difficulty,
    xp: parsed.xp,
    objectives: parsed.objectives,
    requirements: parsed.requirements,
    hints: parsed.hints,
    seed: parsed.seed,
    validator: parsed.validator,
    timeLimit: parsed.timeLimit,
    validatorKey: `${techSlug}/${moduleSlug}`,
  };

  const validatorRel = path.join("content", techSlug, "modules", moduleSlug, "validator.ts");
  if (existsSync(path.join(ROOT, validatorRel))) {
    const bundled = await bundleValidator(techSlug, moduleSlug);
    if (bundled) {
      challenge.validatorPath = bundled.path;
      validatorSources.set(`${techSlug}/${moduleSlug}`, bundled.source);
    }
  }

  return challenge;
}

async function buildContent(): Promise<void> {
  mkdirSync(MDX_OUT_DIR, { recursive: true });
  mkdirSync(VALIDATORS_OUT_DIR, { recursive: true });

  const technologies: RegisteredTechnology[] = [];
  const modules: RegisteredModule[] = [];
  const lessons: RegisteredLesson[] = [];
  const searchDocuments: SearchDocument[] = [];
  const moduleAggs = new Map<string, ModuleAgg>();
  const lessonEntries: LessonEntry[] = [];
  const docTexts = new Map<string, Partial<Record<TechnologyDocName, string>>>();
  const knownLessonSlugs = new Set<string>();

  // 1. Discover technologies.
  for (const relPath of contentGlob("content/*/tech.json")) {
    const techSlug = path.posix.basename(path.posix.dirname(relPath));
    const data = await safeRun(relPath, () => readJson(path.join(ROOT, relPath)));
    if (!data) continue;
    const parsed = await safeRun(`${techSlug}/tech.json`, () => technologySchema.parse(data));
    if (!parsed) continue;

    if (parsed.slug !== techSlug) {
      pushError(`content/${techSlug}/tech.json: slug mismatch — file is in "${techSlug}/" but declares "${parsed.slug}"`);
      continue;
    }
    if (!iconMap[parsed.icon]) {
      pushError(`content/${techSlug}/tech.json: icon "${parsed.icon}" is not registered in lib/icons.ts`);
    }
    for (const pathId of parsed.pathIds) {
      if (!learningPaths.some((p) => p.slug === pathId)) {
        pushError(`content/${techSlug}/tech.json: unknown learning path "${pathId}" in pathIds`);
      }
    }

    technologies.push({ ...parsed, moduleCount: 0, lessonCount: 0, docs: {} });
  }

  // 2. Discover lessons.
  for (const relPath of contentGlob("content/*/modules/*/lesson.mdx")) {
    const techSlug = path.posix.basename(
      path.posix.dirname(path.posix.dirname(path.posix.dirname(relPath))),
    );
    const moduleSlug = path.posix.basename(path.posix.dirname(relPath));

    if (!technologies.some((t) => t.slug === techSlug)) {
      pushError(`${relPath}: unknown technology "${techSlug}" (missing tech.json)`);
      continue;
    }

    const raw = await safeRun(relPath, () => matter(readFileSync(path.join(ROOT, relPath), "utf8")));
    if (!raw) continue;
    const meta = await safeRun(`${relPath} frontmatter`, () => lessonFrontmatterSchema.parse(raw.data));
    if (!meta) continue;
    const compiled = await safeRun(`${relPath} mdx`, () => compileMdx(raw.content));
    if (!compiled) continue;

    const outRel = `mdx/${techSlug}/modules/${moduleSlug}/lesson.js`;
    writeCompiled(outRel, compiled.code);

    const lesson: RegisteredLesson = {
      title: meta.title,
      slug: meta.slug,
      technologySlug: techSlug,
      moduleSlug,
      order: meta.order,
      difficulty: meta.difficulty,
      readingTime: meta.readingTime,
      xp: meta.xp,
      tags: meta.tags,
      prerequisites: meta.prerequisites,
      description: meta.description,
      status: meta.status,
      mdxPath: outRel,
      headings: compiled.headings,
    };

    const exampleRel = findExamplePath(techSlug, moduleSlug);
    if (exampleRel) {
      const extension = path.extname(exampleRel);
      const exampleOutRel = `mdx/${techSlug}/modules/${moduleSlug}/example${extension}`;
      copyFileSync(path.join(ROOT, exampleRel), path.join(OUT_DIR, exampleOutRel));
      lesson.examplePath = exampleOutRel;
    }

    const challenge = await parseChallenge(techSlug, moduleSlug);
    if (challenge) lesson.challenge = challenge;

    const key = `${techSlug}/${moduleSlug}`;
    let agg = moduleAggs.get(key);
    if (!agg) {
      agg = { techSlug, moduleSlug, meta: null, lessons: [] };
      moduleAggs.set(key, agg);
    }
    agg.lessons.push(lesson);
    knownLessonSlugs.add(meta.slug);

    const moduleJsonRel = path.join("content", techSlug, "modules", moduleSlug, "module.json");
    if (existsSync(path.join(ROOT, moduleJsonRel))) {
      const moduleData = await safeRun(moduleJsonRel, () => readJson(path.join(ROOT, moduleJsonRel)));
      const parsedModule = moduleData
        ? await safeRun(`${moduleJsonRel} schema`, () => moduleSchema.parse(moduleData))
        : undefined;
      if (parsedModule) {
        if (parsedModule.slug !== moduleSlug) {
          pushError(`${moduleJsonRel}: slug mismatch — file is in "${moduleSlug}/" but declares "${parsedModule.slug}"`);
        } else {
          agg.meta = { ...parsedModule, technologySlug: techSlug };
        }
      }
    }

    const techOrder = technologies.find((t) => t.slug === techSlug)?.order ?? Number.MAX_SAFE_INTEGER;
    lessonEntries.push({ lesson, techOrder });
  }

  // 3. Finalize modules and global lesson ordering.
  const moduleOrderByKey = new Map<string, number>();

  for (const [key, agg] of moduleAggs) {
    agg.lessons.sort((a, b) => a.order - b.order);

    const first = agg.lessons[0];
    const meta: ModuleMeta = agg.meta ?? {
      slug: agg.moduleSlug,
      title: first?.title ?? agg.moduleSlug,
      description: first?.description ?? "",
      order: agg.lessons.reduce((min, l) => Math.min(min, l.order), Number.MAX_SAFE_INTEGER),
      technologySlug: agg.techSlug,
    };
    moduleOrderByKey.set(key, meta.order);

    modules.push({
      ...meta,
      lessonSlugs: agg.lessons.map((l) => l.slug),
      lessonCount: agg.lessons.length,
    });
  }

  modules.sort((a, b) => {
    const techOrder = (slug: string) => technologies.find((t) => t.slug === slug)?.order ?? 0;
    return techOrder(a.technologySlug) - techOrder(b.technologySlug) || a.order - b.order;
  });

  for (const entry of lessonEntries) {
    lessons.push(entry.lesson);
  }

  lessons.sort((a, b) => {
    const techOrder = (slug: string) => technologies.find((t) => t.slug === slug)?.order ?? 0;
    const moduleOrder = (slug: string, module: string) =>
      moduleOrderByKey.get(`${slug}/${module}`) ?? 0;
    return (
      techOrder(a.technologySlug) - techOrder(b.technologySlug) ||
      moduleOrder(a.technologySlug, a.moduleSlug) - moduleOrder(b.technologySlug, b.moduleSlug) ||
      a.order - b.order
    );
  });

  // 4. Duplicate/consistency checks.
  const slugOwners = new Map<string, string>();
  for (const lesson of lessons) {
    const owner = slugOwners.get(lesson.slug);
    if (owner) {
      pushError(`duplicate lesson slug "${lesson.slug}" in "${owner}" and "${lesson.technologySlug}/${lesson.moduleSlug}"`);
    } else {
      slugOwners.set(lesson.slug, `${lesson.technologySlug}/${lesson.moduleSlug}`);
    }
    for (const prereq of lesson.prerequisites) {
      if (!knownLessonSlugs.has(prereq)) {
        pushError(`lesson "${lesson.slug}" references unknown prerequisite "${prereq}"`);
      }
    }
  }

  // 5. Technology guides.
  for (const tech of technologies) {
    const texts: Partial<Record<TechnologyDocName, string>> = {};
    for (const docName of TECH_DOC_NAMES) {
      const rel = path.join("content", tech.slug, `${docName}.mdx`);
      if (!existsSync(path.join(ROOT, rel))) continue;
      const source = await safeRun(rel, () => readFileSync(path.join(ROOT, rel), "utf8"));
      if (!source) continue;
      const compiled = await safeRun(`${rel} mdx`, () => compileMdx(source));
      if (!compiled) continue;
      writeCompiled(`mdx/${tech.slug}/${docName}.js`, compiled.code);
      tech.docs[docName] = `mdx/${tech.slug}/${docName}.js`;
      texts[docName] = compiled.text;
    }
    docTexts.set(tech.slug, texts);

    tech.moduleCount = modules.filter((m) => m.technologySlug === tech.slug).length;
    tech.lessonCount = lessons.filter((l) => l.technologySlug === tech.slug).length;
  }

  // 6. Search documents.
  for (const tech of technologies) {
    const docContent = Object.values(docTexts.get(tech.slug) ?? {}).join(" ");
    searchDocuments.push({
      id: `technology:${tech.slug}`,
      type: "technology",
      title: tech.name,
      description: tech.description,
      slug: tech.slug,
      url: `/technologies/${tech.slug}`,
      tags: tech.tags,
      content: normalize([tech.description, docContent, tech.tags.join(" ")]),
    });
  }
  for (const mod of modules) {
    searchDocuments.push({
      id: `module:${mod.technologySlug}:${mod.slug}`,
      type: "module",
      title: mod.title,
      description: mod.description,
      slug: mod.slug,
      url: `/learn/${mod.technologySlug}/${mod.slug}`,
      technologySlug: mod.technologySlug,
      tags: [],
      content: normalize([mod.description]),
    });
  }
  for (const lesson of lessons) {
    if (lesson.status === "draft") continue;
    const text = lesson.headings.map((h) => h.text).join(" ");
    searchDocuments.push({
      id: `lesson:${lesson.slug}`,
      type: "lesson",
      title: lesson.title,
      description: lesson.description,
      slug: lesson.slug,
      url: `/learn/${lesson.technologySlug}/${lesson.moduleSlug}/${lesson.slug}`,
      technologySlug: lesson.technologySlug,
      moduleSlug: lesson.moduleSlug,
      tags: lesson.tags,
      content: normalize([lesson.description, text, lesson.tags.join(" ")]),
    });
  }

  // 7. Emit.
  emitRegistry(technologies, modules, lessons);
  emitSearchIndex(searchDocuments);
  emitValidatorSources();

  const published = lessons.filter((l) => l.status !== "draft").length;
  console.log(
    `[content] ok — ${technologies.length} technologies, ${modules.length} modules, ${published} published lessons`,
  );
}

function normalize(parts: string[]): string {
  return parts.filter(Boolean).join(" ").replace(/\s+/g, " ").trim();
}

function emitRegistry(
  technologies: RegisteredTechnology[],
  modules: RegisteredModule[],
  lessons: RegisteredLesson[],
): void {
  const source = `/* AUTO-GENERATED by scripts/build-content.ts — do not edit. */
import type { RegisteredLesson, RegisteredModule, RegisteredTechnology } from "@/types/content";

export const technologies: RegisteredTechnology[] = ${JSON.stringify(technologies, null, 2)};

export const modules: RegisteredModule[] = ${JSON.stringify(modules, null, 2)};

export const lessons: RegisteredLesson[] = ${JSON.stringify(lessons, null, 2)};

export function getTechnology(slug: string): RegisteredTechnology | undefined {
  return technologies.find((t) => t.slug === slug);
}

export function getModule(technologySlug: string, moduleSlug: string): RegisteredModule | undefined {
  return modules.find((m) => m.technologySlug === technologySlug && m.slug === moduleSlug);
}

export function getModulesByTechnology(technologySlug: string): RegisteredModule[] {
  return modules.filter((m) => m.technologySlug === technologySlug);
}

export function getLessonsByTechnology(technologySlug: string): RegisteredLesson[] {
  return lessons.filter((l) => l.technologySlug === technologySlug);
}

export function getLessonsByModule(technologySlug: string, moduleSlug: string): RegisteredLesson[] {
  return lessons.filter((l) => l.technologySlug === technologySlug && l.moduleSlug === moduleSlug);
}

export function getLessonBySlug(slug: string): RegisteredLesson | undefined {
  return lessons.find((l) => l.slug === slug);
}
`;
  writeFileSync(REGISTRY_PATH, source, "utf8");
}

function emitSearchIndex(documents: SearchDocument[]): void {
  const index = {
    version: 1,
    generatedAt: new Date().toISOString(),
    documents,
  };
  writeFileSync(SEARCH_INDEX_PATH, JSON.stringify(index, null, 2), "utf8");
}

/**
 * Emit `lib/generated/validator-sources.ts` — the raw IIFE source of every
 * bundled validator, keyed by `validatorKey`. The ChallengeRunner embeds these
 * into the sandbox `srcdoc`. Keys/values are JSON.stringify-escaped so the
 * source is a safe TS string literal.
 */
function emitValidatorSources(): void {
  const entries = [...validatorSources.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, source]) => `  ${JSON.stringify(key)}: ${JSON.stringify(source)},`)
    .join("\n");

  const modulePath = path.relative(ROOT, VALIDATOR_SOURCES_PATH).split(path.sep).join("/");
  const source = `/* AUTO-GENERATED by scripts/build-content.ts — do not edit. */
/**
 * Raw IIFE source of every bundled content validator, keyed by
 * \`${"${techSlug}/${moduleSlug}"}\`. The ChallengeRunner embeds these sources
 * into the sandboxed iframe \`srcdoc\` so validators execute with the learner's
 * code inside an opaque origin.
 */
export const validatorSources: Record<string, string> = {
${entries}
};
`;
  writeFileSync(VALIDATOR_SOURCES_PATH, source, "utf8");
  console.log(`[content] validator sources emitted to ${modulePath} (${validatorSources.size})`);
}

async function main(): Promise<void> {
  console.log("[content] building registry from content/ …");
  await buildContent();
  if (errors.length > 0) {
    console.error(`[content] build failed with ${errors.length} error(s):`);
    for (const error of errors) console.error(`  - ${error}`);
    process.exit(1);
  }
}

main().catch((error) => {
  console.error("[content] unexpected failure:", error);
  process.exit(1);
});
